# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: enable
cache: packages
warnings_are_errors: false

r_packages:
 - covr

before_install:
  - cd $REPO_TO_TEST

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

env:
  matrix:
        - REPO_TO_TEST=tmcRtestrunner

after_success:
  - Rscript -e 'library(covr);coveralls()'
